name: Otomatik Bot Calistirici

on:
  schedule:
    # UTC saat dilimine göredir.
    # Örnek: Her gün Türkiye saatiyle 09:00 da çalışması için (UTC 06:00):
    - cron: '0 6 * * *'
  workflow_dispatch: # Github arayüzünden manuel tetiklemek için button ekler

jobs:
    run-automation:
      runs-on: ubuntu-latest

      steps:
        - name: Repoyu klonla
          uses: actions/checkout@v4


        - name: Python ortamını kur
          uses: actions/setup-python@v5
          with:
            python-version: '3.11'

        - name: Bağımlılıkları Yükle
          run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

        - name: Scripti Çalıştır
          env:
            # Eğer gizli API anahtarları veya veritabanı bilgileri varsa buraya tanımlanır:
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          run: |
            python main.py